local capability = require("mugshot.capability")

describe("capability._verdict", function()
    it("is ok only when image, terminal and tmux all pass", function()
        local v = capability._verdict(true, true, true)
        assert.is_true(v.ok)
        assert.is_nil(v.reason)
    end)

    it("blames image.nvim first when it is missing", function()
        local v = capability._verdict(false, true, true)
        assert.is_false(v.ok)
        assert.is_truthy(v.reason:find("image.nvim", 1, true))
    end)

    it("blames the terminal when image is present but the protocol is not", function()
        local v = capability._verdict(true, false, true)
        assert.is_false(v.ok)
        assert.is_truthy(v.reason:find("kitty graphics protocol", 1, true))
    end)

    it("surfaces the tmux reason verbatim when only passthrough is off", function()
        local v = capability._verdict(true, true, false, "passthrough is off")
        assert.is_false(v.ok)
        assert.are.equal("passthrough is off", v.reason)
    end)

    it("carries the three component booleans through", function()
        local v = capability._verdict(true, false, true)
        assert.is_true(v.image)
        assert.is_false(v.terminal)
        assert.is_true(v.tmux_ok)
    end)
end)
